export const availablePromptTemplates = [
    {id: "idea", description: "Your story idea from the overview page"},
    {id: "botId", description: "The personality of your ghost writer."},
    {id: "json", description: "Instructions for the bot to output everything in JSON.  This should be included in every system prompt along with the appropriate interface."},
    {id: "styleGuide", description: "Instructions for the bot on how to write its prose."},
    {id: "outline.interface", description: "How the bot should structure its outline data.  DO NOT ALTER THIS, and make sure it is included in the outline prompt templates."},
    {id: "story.details.full", description: "Full details for the story.  By default, includes everything on the overview, locations, and characters page."},
    {id: "locations.interface", description: "How the bot should structure its location data.  DO NOT ALTER THIS, and make sure it is included in the locations prompt templates."},
    {id: "characters.interface", description: "How the bot should structure its character data.  DO NOT ALTER THIS, and make sure it is included in the characters prompt templates."},
    {id: "character.gen.notes", description: "Notes on how to generate characters"},
    {id: "acts.interface", description: "How the bot should structure its acts data.  DO NOT ALTER THIS, and make sure it is included in the acts prompt templates."},
    {id: "chapters.interface", description: "How the bot should structure its chapter data.  DO NOT ALTER THIS, and make sure it is included in the chapters prompt templates."},
    {id: "scenes.interface", description: "How the bot should structure its scenes data.  DO NOT ALTER THIS, and make sure it is included in the scenes prompt templates."},
    {id: "beats.interface", description: "How the bot should structure its beats data.  DO NOT ALTER THIS, and make sure it is included in the beats prompt templates."},
    {id: "prose.interface", description: "How the bot should structure its prose data.  DO NOT ALTER THIS, and make sure it is included in the prose prompt templates."},
    {id: "story.info", description: "The information shown on the overview page."},
    {id: "story.locations", description: "Information about all of the locations"},
    {id: "story.characters", description: "Informaton about all of the characters"},
    {id: "previousActs", description: "Summary of all previous acts.  Can only be used in chapter, scene, beat, and prose user prompts."},
    {id: "previousChapters", description: "Summary of all previous chapters in the current act.  Can only be used in scene, beat, and prose user prompts."},
    {id: "previousScenes", description: "Summary of all previous scenes in the current chapter.  Can only be used in beat, and prose user prompts."},
    {id: "previousBeats", description: "Text of all previous beats in the current scene.  Can only be used in prose user prompts."},
    {id: "currentAct", description: "Outline of the current act.  Can only be use in chapter, scene, beat, and prose user prompts."},
    {id: "currentChapter", description: "Outline of the current chapter.  Can only be use in scene, beat, and prose user prompts."},
    {id: "currentScene", description: "Outline of the current scene.  Can only be use in beat, and prose user prompts."},
    {id: "currentBeat", description: "Outline of the current beat.  Can only be use in prose user prompts."},
    {id: "nextActs", description: "Outlines of the subsequent acts.  Can only be used in chapter, scene, beat, and prose user prompts."},
    {id: "nextChapters", description: "Outlines of the subsequent chapters in the current act.  Can only be used in scene, beat, and prose user prompts."},
    {id: "nextScenes", description: "Outlines of the subsequent scenes in the current chapter.  Can only be used in beat, and prose user prompts."},
    {id: "nextBeats", description: "Outlines of the subsequent beats in the current scene.  Can only be used in prose user prompts."},
    {id: "summary.interface", description: "How the bot should structure its summary data.  DO NOT ALTER THIS, and make sure it is included in the summary prompt templates."}
]
